"""Write a complete OpenROAD-flow-scripts (ORFS) platform for ADAMAS-PDK-0 (project P-2) [ajayi2019].

Files: tech LEF, cell LEF, timed Liberty, cell GDS, setRC.tcl, pdn.tcl, make_tracks.tcl, fastroute.tcl, tapcell.tcl,
a KLayout tech template, and config.mk. Wire parasitics are order-of-magnitude estimates for 2 um lines on diamond
(epsilon_r = 5.7 [wort2008]); they are placeholders until the PDK-0 monitor die is measured (chapter E2).
"""
from __future__ import annotations
from pathlib import Path
from . import pdk0, stdcells

CONFIG = """# ORFS platform: ADAMAS-PDK-0 (diamond, p-channel enhancement/depletion logic, lambda = 1 um). Generated by adamas.orfs_platform.
export PROCESS = 2000
export TECH_LEF = $(PLATFORM_DIR)/adamas_pdk0.tech.lef
export SC_LEF   = $(PLATFORM_DIR)/adamas_ed.lef
export LIB_FILES = $(PLATFORM_DIR)/adamas_ed_timed.lib
export GDS_FILES = $(PLATFORM_DIR)/adamas_ed.gds
export PLACE_SITE = core
export DONT_USE_CELLS = FILL1
export FILL_CELLS = FILL1
export TIEHI_CELL_AND_PORT = TIEHI Y
export TIELO_CELL_AND_PORT = TIELO Y
export MIN_BUF_CELL_AND_PORTS = BUF A Y
export ABC_DRIVER_CELL = BUF
export ABC_LOAD_IN_FF = 2
export IO_PLACER_H = METAL2
export IO_PLACER_V = GATE
export PDN_TCL = $(PLATFORM_DIR)/pdn.tcl
export TAPCELL_TCL = $(PLATFORM_DIR)/tapcell.tcl
export FASTROUTE_TCL = $(PLATFORM_DIR)/fastroute.tcl
export MIN_ROUTING_LAYER = GATE
export MIN_CLK_ROUTING_LAYER = GATE
export MAX_ROUTING_LAYER = METAL2
export KLAYOUT_TECH_FILE = $(PLATFORM_DIR)/adamas_pdk0.lyt
export PWR_NETS_VOLTAGES ?= VDD 10
export GND_NETS_VOLTAGES ?= VSS 0.0
export IR_DROP_LAYER ?= METAL2
export PLACE_DENSITY ?= 0.45
export MACRO_PLACE_HALO ?= 20 20
"""

SET_RC = """# Per-unit-length wire parasitics, 2 um lines (kohm/um, fF/um); placeholder estimates, see adamas.orfs_platform
set_layer_rc -layer GATE -resistance 5.0e-05 -capacitance 0.15
set_layer_rc -layer METAL2 -resistance 2.5e-05 -capacitance 0.15
set_layer_rc -via CONT -resistance 1.0e-03
set_wire_rc -signal -layer METAL2
set_wire_rc -clock -layer METAL2
"""

PDN = """add_global_connection -net {VDD} -inst_pattern {.*} -pin_pattern {^VDD$} -power
add_global_connection -net {VSS} -inst_pattern {.*} -pin_pattern {^VSS$} -ground
global_connect
set_voltage_domain -name {CORE} -power {VDD} -ground {VSS}
# Two routing layers only: vertical GATE stripes across the core would short to transistor gates inside the cells, so
# power enters through a core ring (METAL2 horizontal, GATE vertical) and the METAL2 follow-pin rails extend into it.
define_pdn_grid -name {grid} -voltage_domains {CORE}
add_pdn_ring -grid {grid} -layers {METAL2 GATE} -widths {4 4} -spacings {4 4} -core_offsets {4 4}
add_pdn_stripe -grid {grid} -layer {METAL2} -width {3} -followpins -extend_to_core_ring
add_pdn_connect -grid {grid} -layers {GATE METAL2}
"""

TRACKS = f"""make_tracks GATE -x_offset {stdcells.TRACK_OFFSET} -x_pitch {stdcells.TRACK_PITCH} -y_offset {stdcells.TRACK_OFFSET} -y_pitch {stdcells.TRACK_PITCH}
make_tracks METAL2 -x_offset {stdcells.TRACK_OFFSET} -x_pitch {stdcells.TRACK_PITCH} -y_offset {stdcells.TRACK_OFFSET} -y_pitch {stdcells.TRACK_PITCH}
"""

FASTROUTE = """set_global_routing_layer_adjustment GATE-METAL2 0.3
set_routing_layers -signal $::env(MIN_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER)
set_routing_layers -clock $::env(MIN_CLK_ROUTING_LAYER)-$::env(MAX_ROUTING_LAYER)
"""

TAPCELL = "# PDK-0 has no wells: the diamond substrate is an insulator, so no tap or endcap cells are needed [kawarada2014].\n"

LYT = """<?xml version="1.0" encoding="utf-8"?>
<technology>
 <name>adamas_pdk0</name>
 <description>ADAMAS-PDK-0 diamond technology</description>
 <dbu>0.001</dbu>
 <base-path>./platforms/adamas_pdk0/</base-path>
 <add-other-layers>true</add-other-layers>
 <reader-options>
  <lefdef>
   <read-all-layers>true</read-all-layers>
   <layer-map>layer_map('OUTLINE : 235/0';'GATE : 4/0';'GATE.PIN : 4/0';'GATE.LABEL : 4/0';'CONT : 5/0';'CONT.PIN : 5/0';'METAL2 : 6/0';'METAL2.PIN : 6/0';'METAL2.LABEL : 6/0')</layer-map>
   <dbu>0.001</dbu>
   <produce-net-names>true</produce-net-names>
   <produce-inst-names>true</produce-inst-names>
   <produce-cell-outlines>true</produce-cell-outlines>
   <cell-outline-layer>OUTLINE</cell-outline-layer>
   <produce-via-geometry>true</produce-via-geometry>
   <produce-pins>true</produce-pins>
   <pins-suffix>.PIN</pins-suffix>
   <produce-obstructions>false</produce-obstructions>
   <produce-labels>true</produce-labels>
   <labels-suffix>.LABEL</labels-suffix>
   <produce-routing>true</produce-routing>
   <lef-files>adamas_pdk0.tech.lef</lef-files>
  </lefdef>
 </reader-options>
 <connectivity>
  <connection>GATE,CONT,METAL2</connection>
 </connectivity>
</technology>
"""


def write(out_dir: str | Path) -> list[Path]:
    d = Path(out_dir); d.mkdir(parents=True, exist_ok=True)
    stdcells.write_tech_lef(str(d / "adamas_pdk0.tech.lef"))
    stdcells.write_lef(str(d / "adamas_ed.lef"))
    stdcells.write_liberty(str(d / "adamas_ed_timed.lib"))
    cells = [stdcells.cell_layout(n) for n in stdcells.CELLS]
    lib = pdk0.Cell("ADAMAS_ED_LIB")
    for i, c in enumerate(cells):
        lib.ref(c, i * 100.0, 0.0)
    pdk0.write_gds(str(d / "adamas_ed.gds"), [lib] + cells, "ADAMAS_ED_LIB")
    for name, text in (("config.mk", CONFIG), ("setRC.tcl", SET_RC), ("pdn.tcl", PDN), ("make_tracks.tcl", TRACKS),
                       ("fastroute.tcl", FASTROUTE), ("tapcell.tcl", TAPCELL), ("adamas_pdk0.lyt", LYT)):
        (d / name).write_text(text)
    return sorted(d.iterdir())
