"""Numbers for the preprint (paper/adamas.tex), computed from the package so text and code cannot disagree.

    python -m adamas.paper      writes paper/numbers.tex (LaTeX macros), then  make paper  builds the PDF.
Results that need long Monte Carlo runs (circuit-level break-even readout times) are read from the tables that
chapters E6 and E10 already store in docs/data, or quoted from those sections where noted.
"""
from __future__ import annotations
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def numbers() -> dict:
    from scipy.optimize import brentq
    from . import converter, gate_budget, materials, photophysics, power, resource
    N = {}
    foms = materials.normalized_foms()
    N["BFOMratio"] = f"{foms['Diamond']['BFOM']:,.0f}"
    N["KappaRatio"] = f"{materials.MATERIALS['Diamond'].kappa_w_cmk / materials.MATERIALS['Si'].kappa_w_cmk:.1f}"
    m = power.MEASURED_DIAMOND["saha2022"]
    N["MeasuredOverSi"] = f"{power.ron_sp_mohm_cm2(materials.MATERIALS['Si'], m['bv_v']) / m['ron_mohm_cm2']:.0f}"
    N["BestBV"] = f"{max(v['bv_v'] for v in power.MEASURED_DIAMOND.values()):.0f}"
    for key, name in [("Si", "LossSi"), ("4H-SiC", "LossSiC"), ("GaN", "LossGaN"), ("Diamond", "LossDiamond")]:
        N[name] = f"{converter.material_switch(key, 1200, 800, 300, 20e3).p_total_w:.1f}"
    N["LossDiamondMeasured"] = f"{converter.material_switch('Diamond', 1200, 800, 300, 20e3, measured='saha2022').p_total_w:.0f}"
    g = gate_budget.published_check()
    N["GateTimeUs"] = f"{g.t_gate_us:.0f}"; N["FcohPublished"] = f"{g.f_coherent:.3f}"
    N["qForSixtySeven"] = f"{brentq(lambda q: gate_budget.published_check(q).fidelity - 0.67, 0.5, 1.0):.2f}"
    N["qForEightyTwo"] = f"{brentq(lambda q: gate_budget.published_check(q).fidelity - 0.82, 0.5, 1.0):.2f}"
    N["ReadoutContrast"] = f"{100 * photophysics.readout_contrast():.0f}"; N["Polarization"] = f"{100 * photophysics.polarization():.0f}"
    t = resource.table()
    lam = {int(tr): r["Lambda"] for tr, r in zip(t["readout_us"], t["fits"]["1000"])}
    N["LambdaFast"] = f"{lam[100]:.2f}"; N["LambdaMs"] = f"{lam[1000]:.2f}"; N["LambdaTenMs"] = f"{lam[10000]:.2f}"
    n, st = resource.WORKLOADS["RSA-2048 scale (6,000 logical, 3×10⁹ steps)"]
    e1 = resource.estimate(n, st, 1000.0, 1000.0, t=t); e2 = resource.estimate(n, st, 100.0, 1000.0, t=t); sc = resource.superconducting_reference(n, st)
    N["RSADistance"] = str(e1.distance); N["RSAQubitsM"] = f"{e1.physical_qubits / 1e6:.0f}"; N["RSADieMm"] = f"{e1.die_side_mm:.1f}"
    N["RSAYears"] = f"{e1.runtime_hours / 8766:.1f}"; N["RSAYearsFast"] = f"{e2.runtime_hours / 8766:.1f}"; N["RSADaysSC"] = f"{sc.runtime_hours / 24:.0f}"
    net = ROOT / "circuits" / "digital" / "dia4_netlist.v"
    N["DiaCells"] = str(len(re.findall(r"^\s*(BUF|INV|NAND2|NOR2|NOR3|DFF)\s", net.read_text(), re.M))) if net.exists() else "about 320"
    import sys
    sys.path.insert(0, str(ROOT / "tools")); from refs_common import load
    refs = load(); N["NumRefs"] = str(len(refs)); N["NumVerified"] = str(sum(r.status == "V" for r in refs))
    N["NumFigures"] = str(len(list((ROOT / "docs" / "img").glob("fig*.png"))))
    from . import uncertainty
    mp, mq = uncertainty.monte_carlo("power", 4000), uncertainty.monte_carlo("quantum", 4000)
    N["UncPowerPten"], N["UncPowerPfifty"], N["UncPowerPninety"] = (f"{mp[k]:.1f}" for k in ("p10", "p50", "p90"))
    N["UncQPten"], N["UncQPfifty"], N["UncQPninety"] = (f"{mq[k]:.1f}" for k in ("p10", "p50", "p90"))
    from . import validation
    sv = validation.summary(); N["ValChecks"] = str(sum(sv.values())); N["ValPass"] = str(sv["pass"])
    from . import xzzx_native
    S = xzzx_native.cached_study(); i = S["etas"].index(100); j = S["t_read_us"].index(1000)
    N["ThrCSSBias"] = f"{100 * S['thr']['css'][i]:.2f}"; N["ThrXZZXBias"] = f"{100 * S['thr']['xzzx'][i]:.2f}"; N["ThrDepol"] = f"{100 * S['thr']['css'][0]:.2f}"
    N["NativeGain"] = f"{S['nv']['css'][7][j] / S['nv']['xzzx'][7][j]:.0f}"
    N["BreakevenStdMs"] = "100"; N["BreakevenXZZXMs"] = "1000"          # chapter E6, sections E6.1c and E6.1d
    return N


def write(path: str | Path = ROOT / "paper" / "numbers.tex") -> Path:
    p = Path(path); p.parent.mkdir(exist_ok=True)
    lines = ["% Generated by  python -m adamas.paper  from the ADAMAS package. Do not edit by hand."]
    lines += [f"\\newcommand{{\\{k}}}{{{v.replace(',', '{,}')}}}" for k, v in numbers().items()]
    p.write_text("\n".join(lines) + "\n", encoding="utf-8"); return p


if __name__ == "__main__":
    print("wrote", write())
