"""Keeps the README's key-findings block in sync with the package (between <!-- findings:start/end --> markers)."""
from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
START, END = "<!-- findings:start -->", "<!-- findings:end -->"


def block() -> str:
    from .site import findings
    F = findings()
    rows = [("Power switches", f"Diamond's ideal figure of merit is **{F['BFOMratio']}×** silicon's; with honest material uncertainty its EV-inverter loss advantage over silicon carbide is a median **{F['UncPowerPfifty']}×** ({F['UncPowerPten']}× to {F['UncPowerPninety']}×).", "[Confidence](docs/VALIDATION.md)"),
            ("Two-qubit gates", f"Coherence would allow a Bell fidelity of **{F['FcohPublished']}**; the measured 0.67 means the NV⁻ charge state was ready only **{F['qForSixtySeven']}** of the time. Preparation, not coherence, is the bottleneck.", "[E5](docs/expert/E5_nv_qubit_engineering.md)"),
            ("Error correction", f"With strongly biased noise the native XZZX code's threshold rises to **{F['ThrXZZXBias']}%** while the standard code falls to {F['ThrCSSBias']}%.", "[E6.1e](docs/expert/E6_error_correction_and_system_architecture.md)"),
            ("Machine size", f"A factoring-scale room-temperature machine fits on a **{F['RSADieMm']} mm** die but runs **{F['RSAYears']} years** at 1 ms readout ({F['UncQPten']} to {F['UncQPninety']} years with uncertainty). If gate noise is biased, the standard code needs {F['RSAQubitsMCSSBiased']} M qubits and the XZZX code **{F['RSAQubitsMXZZX']} M**.", "[E10.5c](docs/expert/E10_scaling_a_room_temperature_quantum_computer.md)"),
            ("Evidence", f"**{F['ValPass']} of {F['ValChecks']}** validation checks pass (the other is an explained discrepancy); {F['NumRefs']} references; {F['NumFigures']} figures regenerated from code.", "[VALIDATION.md](docs/VALIDATION.md)")]
    return "\n".join([START, "| | Result (generated by `adamas build docs`) | Details |", "|---|---|---|"] + [f"| **{a}** | {b} | {c} |" for a, b, c in rows] + [END])


def update(path: Path = ROOT / "README.md") -> bool:
    s = path.read_text(encoding="utf-8"); a, b = s.index(START), s.index(END) + len(END)
    new = s[:a] + block() + s[b:]
    if new != s:
        path.write_text(new, encoding="utf-8"); return True
    return False


def write() -> str:
    update(); return "README.md (key findings)"
